on:
  pull_request_target:
    types:
    - labeled
  pull_request_review: {}

jobs:
- uses: actions/github-script@v6
  id: check-requirements
  with:
    result-encoding: string
    script: |
      console.log(context);
