on:
  pull_request_target:
    types:
    - labeled
    - unlabeled
  pull_request_review: {}

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: check-requirements
      with:
        result-encoding: string
        script: |
          console.log(context);
          let sizeLabel = context.payload.pull_request.labels.find(label => label.name.startsWith("size/"));
          if (sizeLabel === undefined) {
            console.log("Missing Size Label");
            return;
          }
          let reviewsRequired = 2;
          switch(sizeLabel.name) {
            case "size/S":
              reviewsRequired = 1;
            break;
          }
          let [owner, repo] = context.payload.repository.full_name.split("/");
          let reviews = await octokit.rest.pulls.listReviews({
            owner: owner,
            repo: repo,
            pull_number: context.payload.pull_request.number
          });
          // see https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
          console.log(reviews.data.filter(review => review.state === 'APPROVED' && review.author_association === 'COLLABORATOR'));
