on:
  pull_request_target:
    types:
    - labeled
    - unlabeled
  pull_request_review: {}

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: check-requirements
      with:
        result-encoding: string
        script: |
          const sizeLabel = context.payload.pull_request.labels.find(label => label.name.startsWith("size/"));
          if (sizeLabel === undefined) {
            core.setFailed("Missing Size Label");
            return;
          }
          const [_, size] = label.split("/");
          let reviewsRequired = 2;
          if(size === "XS") {
            reviewsRequired = 1;
          }
          const [owner, repo] = context.payload.repository.full_name.split("/");
          const reviews = await github.rest.pulls.listReviews({
            owner: owner,
            repo: repo,
            pull_number: context.payload.pull_request.number
          });
          // see https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
          const relevantReviews = reviews.data.filter(review => review.state === 'APPROVED' && review.author_association === 'COLLABORATOR'));
          if (relevantReviews.length < reviewsRequired) {
            core.setFailed(`PR of size ${size} requires at least ${reviewsRequired} review(s) from maintainers`);
          }
